apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssl-traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ssl-traefik
subjects:
- kind: ServiceAccount
  name: ssl-traefik
  namespace: traefik
